// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhmDefMBUwqTyifl3ulXSe4GCoBck9KEs',
    appId: '1:893349226567:web:b6472fe689acf2f549a962',
    messagingSenderId: '893349226567',
    projectId: 'projeto-android-03',
    authDomain: 'projeto-android-03.firebaseapp.com',
    databaseURL: 'https://projeto-android-03-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-android-03.firebasestorage.app',
    measurementId: 'G-10Z97VZ004',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwFMGwasgDbRzpNXI5Bc8gmOY6gRDWyZw',
    appId: '1:893349226567:android:44231672d8816ded49a962',
    messagingSenderId: '893349226567',
    projectId: 'projeto-android-03',
    databaseURL: 'https://projeto-android-03-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-android-03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv6tKeqAQNlpmkdjT7hIg49EuPVdknesY',
    appId: '1:893349226567:ios:a414d9cae60461ba49a962',
    messagingSenderId: '893349226567',
    projectId: 'projeto-android-03',
    databaseURL: 'https://projeto-android-03-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-android-03.firebasestorage.app',
    iosBundleId: 'com.example.listaFlutterSemana09',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv6tKeqAQNlpmkdjT7hIg49EuPVdknesY',
    appId: '1:893349226567:ios:a414d9cae60461ba49a962',
    messagingSenderId: '893349226567',
    projectId: 'projeto-android-03',
    databaseURL: 'https://projeto-android-03-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-android-03.firebasestorage.app',
    iosBundleId: 'com.example.listaFlutterSemana09',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhmDefMBUwqTyifl3ulXSe4GCoBck9KEs',
    appId: '1:893349226567:web:354081a56b3a034449a962',
    messagingSenderId: '893349226567',
    projectId: 'projeto-android-03',
    authDomain: 'projeto-android-03.firebaseapp.com',
    databaseURL: 'https://projeto-android-03-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-android-03.firebasestorage.app',
    measurementId: 'G-TG99EBECQX',
  );
}
